"""
analyze_ocr_by_length.py
========================
Breaks down OCR performance by text length bucket (word count) for every
experiment, using the images already generated by evaluate_all.py.

No model loading, no GPU needed for inference — only EasyOCR on saved PNGs.

Output
------
- Console table: exact match and word accuracy per bucket per experiment
- results/metrics/ocr_by_length.json  : raw numbers for generate_plots.py
- results/plots/ocr_by_length.png     : grouped bar chart
"""

import json
import re
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from PIL import Image

# ── paths ─────────────────────────────────────────────────────────────────────
DATA_JSON        = Path("data/test.json")
GENERATED_DIR    = Path("results/generated_images")
METRICS_OUT      = Path("results/metrics/ocr_by_length.json")
PLOT_OUT         = Path("results/plots/ocr_by_length.png")

# ── experiment order (controls row order in table + bar chart) ─────────────────
EXPERIMENT_ORDER = [
    "original_baseline",
    "full_finetune",
    "lora_flux2klein_rank8",
    "lora_flux2klein_rank16",
    "lora_flux2klein_rank32",
    "lora_flux2klein_rank64",
    "lora_cross_attention_rank16",
    "lora_cross_attention_rank32",
    "qlora_cross_attention_rank16",
]

LABELS = {
    "original_baseline":           "Original",
    "full_finetune":               "Full FT",
    "lora_flux2klein_rank8":       "LoRA r8",
    "lora_flux2klein_rank16":      "LoRA r16",
    "lora_flux2klein_rank32":      "LoRA r32",
    "lora_flux2klein_rank64":      "LoRA r64",
    "lora_cross_attention_rank16": "CA-LoRA r16",
    "lora_cross_attention_rank32": "CA-LoRA r32",
    "qlora_cross_attention_rank16":"QLoRA r16",
}

COLORS = {
    "original_baseline":           "#888888",
    "full_finetune":               "#E05C2A",
    "lora_flux2klein_rank8":       "#85B7EB",
    "lora_flux2klein_rank16":      "#378ADD",
    "lora_flux2klein_rank32":      "#2A6FBB",
    "lora_flux2klein_rank64":      "#0F3D80",
    "lora_cross_attention_rank16": "#5DCAA5",
    "lora_cross_attention_rank32": "#0F6E56",
    "qlora_cross_attention_rank16":"#BA7517",
}

# ── word-count buckets ─────────────────────────────────────────────────────────
BUCKETS = [
    ("1 word",   lambda n: n == 1),
    ("2 words",  lambda n: n == 2),
    ("3+ words", lambda n: n >= 3),
]


# ── helpers ────────────────────────────────────────────────────────────────────

def normalize(text: str) -> str:
    text = text.lower()
    text = re.sub(r"[^a-z0-9\s]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def load_test_samples():
    """Return list of {text, word_count, image_index} dicts."""
    with open(DATA_JSON, encoding="utf-8") as f:
        data = json.load(f)
    samples = data if isinstance(data, list) else data.get("data", list(data.values()))
    result = []
    for i, s in enumerate(samples):
        text = s.get("text", "")
        wc   = len(text.split()) if text.strip() else 0
        result.append({"text": text, "word_count": wc, "index": i})
    return result


def find_generated_image(exp_name: str, sample_index: int) -> Path | None:
    """
    Generated images are saved as:
      results/generated_images/<exp>/test/<idx:02d>_<prompt_prefix>.png
    We try both 2-digit (legacy) and 3-digit (>99 samples) prefixes.
    """
    exp_dir = GENERATED_DIR / exp_name / "test"
    if not exp_dir.exists():
        return None
    for fmt in (f"{sample_index:02d}_", f"{sample_index:03d}_"):
        matches = sorted(exp_dir.glob(f"{fmt}*.png"))
        if matches:
            return matches[0]
    return None


def ocr_image(reader, image_path: Path) -> str:
    """Run EasyOCR and return normalized concatenated output."""
    img = np.array(Image.open(image_path).convert("RGB"))
    results = reader.readtext(img, detail=0)
    return normalize(" ".join(results))


def score_sample(ocr_output: str, expected: str):
    """
    Returns (exact_match: bool, word_accuracy: float) for one sample.
    Both operate on normalized strings.
    """
    exp_norm = normalize(expected)
    exact    = exp_norm in ocr_output

    words   = exp_norm.split()
    word_acc = (sum(1 for w in words if w in ocr_output) / len(words)) if words else 0.0

    return exact, word_acc


# ── main ───────────────────────────────────────────────────────────────────────

def main():
    try:
        import easyocr
    except ImportError:
        print("EasyOCR not installed. Run: pip install easyocr --break-system-packages")
        return

    import torch
    reader = easyocr.Reader(['en'], gpu=torch.cuda.is_available(), verbose=False)

    samples = load_test_samples()
    print(f"Loaded {len(samples)} test samples from {DATA_JSON}")

    # Print word-count distribution
    wc_dist = {}
    for s in samples:
        wc_dist[s["word_count"]] = wc_dist.get(s["word_count"], 0) + 1
    print("\nWord-count distribution in test set:")
    for wc in sorted(wc_dist):
        label = f"  {wc} word{'s' if wc != 1 else ''}"
        print(f"{label:<12}: {wc_dist[wc]} samples")

    # Identify which experiments have generated images
    available_exps = [
        e for e in EXPERIMENT_ORDER
        if (GENERATED_DIR / e / "test").exists()
    ]
    print(f"\nFound generated images for: {available_exps}\n")

    # ── collect per-experiment, per-bucket scores ──────────────────────────────
    results = {}   # {exp_name: {bucket_label: {exact: [], word_acc: []}}}

    for exp in available_exps:
        print(f"Processing {exp}...")
        results[exp] = {b[0]: {"exact": [], "word_acc": []} for b in BUCKETS}
        results[exp]["all"] = {"exact": [], "word_acc": []}

        for sample in samples:
            img_path = find_generated_image(exp, sample["index"])
            if img_path is None:
                continue

            ocr_out   = ocr_image(reader, img_path)
            exact, wa = score_sample(ocr_out, sample["text"])

            wc = sample["word_count"]
            for bucket_label, predicate in BUCKETS:
                if predicate(wc):
                    results[exp][bucket_label]["exact"].append(exact)
                    results[exp][bucket_label]["word_acc"].append(wa)
                    break

            results[exp]["all"]["exact"].append(exact)
            results[exp]["all"]["word_acc"].append(wa)

    # ── aggregate ──────────────────────────────────────────────────────────────
    def agg(scores):
        if not scores:
            return None, None
        return round(float(np.mean(scores["exact"])), 4), \
               round(float(np.mean(scores["word_acc"])), 4)

    aggregated = {}
    for exp in available_exps:
        aggregated[exp] = {}
        for bucket_label, _ in BUCKETS:
            em, wa = agg(results[exp][bucket_label])
            n      = len(results[exp][bucket_label]["exact"])
            aggregated[exp][bucket_label] = {"exact": em, "word_acc": wa, "n": n}
        em_all, wa_all = agg(results[exp]["all"])
        aggregated[exp]["all"] = {
            "exact": em_all, "word_acc": wa_all,
            "n": len(results[exp]["all"]["exact"])
        }

    # ── print table ────────────────────────────────────────────────────────────
    bucket_labels = [b[0] for b in BUCKETS] + ["all"]
    col_w = 20

    print("\n" + "="*100)
    print("OCR EXACT MATCH BY TEXT LENGTH")
    print("="*100)
    header = f"{'Experiment':<38}" + "".join(f"{b:>{col_w}}" for b in bucket_labels)
    print(header)
    print("-"*100)
    for exp in available_exps:
        row = f"{exp:<38}"
        for b in bucket_labels:
            v = aggregated[exp][b]["exact"]
            n = aggregated[exp][b]["n"]
            cell = f"{v:.2f} (n={n})" if v is not None else "  N/A"
            row += f"{cell:>{col_w}}"
        print(row)

    print("\n" + "="*100)
    print("OCR WORD ACCURACY BY TEXT LENGTH")
    print("="*100)
    print(header)
    print("-"*100)
    for exp in available_exps:
        row = f"{exp:<38}"
        for b in bucket_labels:
            v = aggregated[exp][b]["word_acc"]
            n = aggregated[exp][b]["n"]
            cell = f"{v:.2f} (n={n})" if v is not None else "  N/A"
            row += f"{cell:>{col_w}}"
        print(row)

    # ── save JSON ──────────────────────────────────────────────────────────────
    METRICS_OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(METRICS_OUT, "w") as f:
        json.dump(aggregated, f, indent=2)
    print(f"\n✓ Saved to {METRICS_OUT}")

    # ── plots ──────────────────────────────────────────────────────────────────
    _plot_heatmap(aggregated, available_exps, bucket_labels[:-1])
    _plot_bars(aggregated, available_exps, bucket_labels[:-1])


def _plot_heatmap(aggregated, experiments, buckets):
    """
    2-panel heatmap: left = exact match, right = word accuracy.
    Rows = experiments, columns = word-count buckets.
    Cell text shows the score; color encodes it (white=0, green=1).
    """
    import matplotlib.colors as mcolors

    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    fig.suptitle("OCR performance by text length",
                 fontsize=14, fontweight="bold", y=1.02)

    panels = [
        ("exact",    "Exact match ↑"),
        ("word_acc", "Word accuracy ↑"),
    ]

    row_labels = [LABELS.get(e, e) for e in experiments]
    cmap = plt.cm.RdYlGn   # red=low, yellow=mid, green=high

    for ax, (metric_key, title) in zip(axes, panels):
        # Build matrix: rows=experiments, cols=buckets
        matrix = np.array([
            [aggregated[exp].get(b, {}).get(metric_key) or 0.0
             for b in buckets]
            for exp in experiments
        ])

        im = ax.imshow(matrix, cmap=cmap, vmin=0, vmax=1, aspect="auto")

        # Cell annotations
        for r in range(len(experiments)):
            for c in range(len(buckets)):
                val = matrix[r, c]
                # Dark text on light cells, light text on dark cells
                text_color = "black" if 0.3 < val < 0.75 else "white" if val >= 0.75 else "black"
                n = aggregated[experiments[r]].get(buckets[c], {}).get("n", 0)
                ax.text(c, r, f"{val:.2f}\nn={n}",
                        ha="center", va="center",
                        fontsize=9, color=text_color, linespacing=1.4)

        ax.set_xticks(range(len(buckets)))
        ax.set_xticklabels(buckets, fontsize=11)
        ax.set_yticks(range(len(experiments)))
        ax.set_yticklabels(row_labels, fontsize=10)
        ax.set_title(title, fontsize=12, fontweight="bold", pad=8)

        plt.colorbar(im, ax=ax, fraction=0.03, pad=0.02)

    plt.tight_layout()
    heatmap_out = PLOT_OUT.parent / "ocr_by_length_heatmap.png"
    heatmap_out.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(heatmap_out, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"✓ Heatmap saved to {heatmap_out}")


def _plot_bars(aggregated, experiments, buckets):
    """Grouped bar chart — one group per bucket, one bar per experiment."""
    fig, axes = plt.subplots(1, 2, figsize=(16, 6))
    fig.suptitle("OCR performance by text length (word count)",
                 fontsize=14, fontweight="bold")

    metrics = [("exact",    "Exact match ↑"),
               ("word_acc", "Word accuracy ↑")]

    x     = np.arange(len(buckets))
    n_exp = len(experiments)
    width = 0.8 / n_exp

    for ax, (metric_key, ylabel) in zip(axes, metrics):
        for i, exp in enumerate(experiments):
            vals = [aggregated[exp].get(b, {}).get(metric_key) or 0.0
                    for b in buckets]
            ns   = [aggregated[exp].get(b, {}).get("n", 0) for b in buckets]
            offset = (i - n_exp / 2 + 0.5) * width
            bars = ax.bar(x + offset, vals, width=width * 0.9,
                          color=COLORS.get(exp, "#999"),
                          label=LABELS.get(exp, exp),
                          edgecolor="white", linewidth=0.5)
            for bar, n in zip(bars, ns):
                if n > 0:
                    ax.text(bar.get_x() + bar.get_width() / 2,
                            bar.get_height() + 0.005,
                            f"n={n}", ha="center", va="bottom",
                            fontsize=7, color="#555")

        ax.set_xticks(x)
        ax.set_xticklabels(buckets, fontsize=11)
        ax.set_ylabel(ylabel, fontsize=11)
        ax.set_ylim(0, 1.05)
        ax.grid(axis="y", linestyle="--", alpha=0.4)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)

    handles, labels_ = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels_, loc="lower center",
               ncol=min(5, n_exp), fontsize=9,
               bbox_to_anchor=(0.5, -0.05))

    plt.tight_layout(rect=[0, 0.06, 1, 1])
    PLOT_OUT.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(PLOT_OUT, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"✓ Bar chart saved to {PLOT_OUT}")


if __name__ == "__main__":
    main()